# Generated by Django 5.1 on 2024-08-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='position',
        ),
        migrations.AddField(
            model_name='customer',
            name='position_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
