# Generated by Django 5.1 on 2024-09-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_image',
            field=models.ImageField(blank=True, default='default_images/default_card_image.jpg', null=True, upload_to='product_images/'),
        ),
    ]
