# Generated by Django 5.1 on 2024-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customer_position_customer_position_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='position_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
